# Generated by Django 3.2 on 2021-05-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_auto_20210530_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
