# Generated by Django 3.2 on 2021-05-30 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0004_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='quantity',
        ),
    ]
