# Generated by Django 3.2 on 2021-06-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0007_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='petType',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(default='Male', max_length=10, null=True),
        ),
    ]
